# ワークフローの名前。 GitHubでは、リポジトリのアクションページにワークフローの名前が表示されます。
# nameを省略すると、GitHubはリポジトリのルートに対するワークフローファイルの相対パスをその値に設定します。
name: actions-sample-go-test

# 必須 ワークフローをトリガーするGitHubイベントの名前。
# 指定できるのは、1つのイベントstring、複数イベントのarray、イベントtypesのarray
on:
  push:
    branches:
      - master
      - releases/**
    tags:
      - v1             # Push events to v1 tag
      - v1.*           # Push events to v1.0, v1.1, and v1.9 tags
  pull_request:
    branches: [ master ]

jobs:

  test-job: # test-jobという名前のjob_id
    name: test-job # GitHubに表示されるジョブの名前
    runs-on: ubuntu-latest
    steps:

    # Goのセットアップ
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    # repositoryの中身にアクセスするためのチェックアウト
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # 依存関係取得
    # -v 実行しているコマンドを表示
    # -t テストを実行する為に必要となるパッケージも同時にダウンロード
    # -d ダウンロードするだけでインストールはしない
    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
